
export const tradingPlans = [
  {
    id: 1,
    name: 'Beginner',
    description: 'Basic plan for new traders.',
    price: 'Spreads from 1.0 pips',
    priceDescription: 'Min. Deposit: $500',
    features: [
      'Access to Forex, Crypto, & Indices',
      'Standard Spreads',
      'Basic Charting Tools',
      '24/5 Customer Support',
    ],
    isPopular: false,
    buttonText: 'Get Started',
  },
  {
    id: 2,
    name: 'Personal',
    description: 'Ideal for individual traders looking for more features.',
    price: 'Spreads from 0.8 pips',
    priceDescription: 'Min. Deposit: $2,500',
    features: [
      'Everything in Beginner',
      'Access to All Markets',
      'Advanced Charting Tools',
      'Weekly Webinars',
    ],
    isPopular: false,
    buttonText: 'Choose Personal',
  },
  {
    id: 3,
    name: 'Standard',
    description: 'A balanced plan with comprehensive tools.',
    price: 'Tighter Spreads',
    priceDescription: 'Min. Deposit: $5,000',
    features: [
      'Everything in Personal',
      'Lower Commission Rates',
      '24/5 Priority Support',
      'Daily AI Trading Insights',
    ],
    isPopular: true,
    buttonText: 'Choose Standard',
  },
  {
    id: 4,
    name: 'Pro',
    description: 'Advanced features for professional traders.',
    price: 'Raw Spreads from 0.0 pips',
    priceDescription: 'Min. Deposit: $10,000',
    features: [
      'Everything in Standard',
      'Lowest Commission Rates',
      'Dedicated Account Manager',
      'Full API Access',
    ],
    isPopular: false,
    buttonText: 'Go Pro',
  },
  {
    id: 5,
    name: 'Corporate',
    description: 'Tailored for corporate clients and institutions.',
    price: 'Contact Us',
    priceDescription: 'Min. Deposit: $50,000',
    features: [
        'All Pro features',
        'Customized Solutions',
        'Institutional Liquidity',
        'Dedicated Support Team'
    ],
    isPopular: false,
    buttonText: 'Contact Sales',
  },
  {
    id: 6,
    name: 'Enterprise',
    description: 'Top-tier plan with maximum benefits and support.',
    price: 'Bespoke Solutions',
    priceDescription: 'Min. Deposit: $100,000+',
    features: [
        'All Corporate features',
        'Bespoke infrastructure',
        'White-label solutions',
        '24/7 VIP Support',
    ],
    isPopular: false,
    buttonText: 'Contact Sales',
  },
];
