
export const tradingPlans = [
  {
    id: 1,
    name: 'Beginner',
    description: 'Perfect for getting started with the basics of trading.',
    price: '$0',
    priceDescription: '/ month',
    features: [
      'Access to Forex & Crypto',
      'Standard Spreads',
      'Basic Charting Tools',
      'Email Support',
    ],
    isPopular: false,
    buttonText: 'Start for Free',
  },
  { id: 2, name: 'Personal' },
  {
    id: 3,
    name: 'Standard',
    description: 'For active traders looking for more tools and better pricing.',
    price: '$49',
    priceDescription: '/ month',
    features: [
      'All Beginner features',
      'Access to All Markets',
      'Lower Spreads',
      'Advanced Charting Tools',
      '24/5 Priority Support',
      'AI Trading Insights',
    ],
    isPopular: true,
    buttonText: 'Choose Standard',
  },
  {
    id: 4,
    name: 'Pro',
    description: 'For experienced traders who need professional-grade features.',
    price: '$99',
    priceDescription: '/ month',
    features: [
      'All Standard features',
      'Raw Spreads from 0.0 pips',
      'Lower Commissions',
      'Copy Trading Access',
      'Dedicated Account Manager',
      'API Access',
    ],
    isPopular: false,
    buttonText: 'Go Pro',
  },
  { id: 5, name: 'Corporate' },
  { id: 6, name: 'Enterprise' },
];
