
export const tradingPlans = [
  {
    id: 1,
    name: 'Beginner',
    description: 'Basic plan for new traders.',
    price: '$0',
    priceDescription: 'commission per trade',
    features: [
      'Min. Deposit: $500',
      'Access to Forex & Crypto',
      'Standard Spreads',
      'Basic Charting Tools',
      'Email Support',
    ],
    isPopular: false,
    buttonText: 'Start Trading',
  },
  {
    id: 2,
    name: 'Personal',
    description: 'Ideal for individual traders looking for more features.',
    price: '$25',
    priceDescription: '/ month',
    features: [
      'Min. Deposit: $2,500',
      'All Beginner features',
      'Access to More Markets',
      'Webinars Access',
    ],
    isPopular: false,
    buttonText: 'Choose Personal',
  },
  {
    id: 3,
    name: 'Standard',
    description: 'A balanced plan with comprehensive tools.',
    price: '$49',
    priceDescription: '/ month',
    features: [
      'Min. Deposit: $5,000',
      'All Personal features',
      'Access to All Markets',
      'Lower Spreads',
      '24/5 Priority Support',
      'AI Trading Insights',
    ],
    isPopular: true,
    buttonText: 'Choose Standard',
  },
  {
    id: 4,
    name: 'Pro',
    description: 'Advanced features for professional traders.',
    price: '$99',
    priceDescription: '/ month',
    features: [
      'Min. Deposit: $10,000',
      'All Standard features',
      'Raw Spreads from 0.0 pips',
      'Lower Commissions',
      'Dedicated Account Manager',
      'API Access',
    ],
    isPopular: false,
    buttonText: 'Go Pro',
  },
  {
    id: 5,
    name: 'Corporate',
    description: 'Tailored for corporate clients and institutions.',
    price: 'Contact Us',
    priceDescription: '',
    features: [
        'Min. Deposit: $50,000',
        'All Pro features',
        'Customized Solutions',
        'Institutional Liquidity'
    ],
    isPopular: false,
    buttonText: 'Contact Sales',
  },
  {
    id: 6,
    name: 'Enterprise',
    description: 'Top-tier plan with maximum benefits and support.',
    price: 'Contact Us',
    priceDescription: '',
    features: [
        'Min. Deposit: $100,000',
        'All Corporate features',
        'Bespoke infrastructure',
        'White-label solutions',
    ],
    isPopular: false,
    buttonText: 'Contact Sales',
  },
];
