
import type { Trader } from './types';

export const mockTraders: Trader[] = [
  {
    id: 'trader_001',
    username: 'CryptoKing',
    market: 'Cryptocurrency',
    risk: 'High',
    profit: '+152.4%',
    copiers: 1245,
    image: 'https://placehold.co/600x400.png',
    avatarSeed: 'CK',
    joined: '2023-01-15',
    strategy: 'High-frequency trading on major crypto pairs, focusing on volatility breakouts. Leverages technical indicators like RSI and MACD for entry and exit points.',
  },
  {
    id: 'trader_002',
    username: 'ForexMaster',
    market: 'Forex',
    risk: 'Medium',
    profit: '+88.7%',
    copiers: 2341,
    image: 'https://placehold.co/600x400.png',
    avatarSeed: 'FM',
    joined: '2022-06-20',
    strategy: 'Swing trading major and minor forex pairs. Strategy is based on fundamental analysis of economic events and central bank policies.',
  },
  {
    id: 'trader_003',
    username: 'SteadyStocks',
    market: 'Stocks',
    risk: 'Low',
    profit: '+45.2%',
    copiers: 3123,
    image: 'https://placehold.co/600x400.png',
    avatarSeed: 'SS',
    joined: '2021-11-10',
    strategy: 'Long-term value investing in blue-chip stocks. Focuses on companies with strong fundamentals, durable competitive advantages, and consistent dividend growth.',
  },
  {
    id: 'trader_004',
    username: 'GoldBug',
    market: 'Commodities',
    risk: 'Medium',
    profit: '+67.9%',
    copiers: 890,
    image: 'https://placehold.co/600x400.png',
    avatarSeed: 'GB',
    joined: '2023-05-01',
    strategy: 'Position trading on precious metals like Gold and Silver. Uses a combination of geopolitical analysis and long-term chart patterns to identify trends.',
  },
    {
    id: 'trader_005',
    username: 'IndexHopper',
    market: 'Indices',
    risk: 'Low',
    profit: '+55.1%',
    copiers: 1854,
    image: 'https://placehold.co/600x400.png',
    avatarSeed: 'IH',
    joined: '2022-09-30',
    strategy: 'Follows major world indices like the S&P 500 and NASDAQ. Employs a passive, diversified approach aiming for consistent, market-aligned returns.',
  },
  {
    id: 'trader_006',
    username: 'VolcanoVibes',
    market: 'Exotic Pairs',
    risk: 'High',
    profit: '-15.5%',
    copiers: 215,
    image: 'https://placehold.co/600x400.png',
    avatarSeed: 'VV',
    joined: '2024-02-12',
    strategy: 'Specializes in high-risk, high-reward exotic currency pairs. This strategy is not for the faint of heart and involves significant potential for loss.',
  },
    {
    id: 'trader_007',
    username: 'GrowthGazer',
    market: 'Tech Stocks',
    risk: 'High',
    profit: '+210.3%',
    copiers: 1987,
    image: 'https://placehold.co/600x400.png',
    avatarSeed: 'GG',
    joined: '2023-08-01',
    strategy: 'Invests in high-growth technology and AI-related stocks. Aims to identify disruptive companies before they become mainstream.',
  },
    {
    id: 'trader_008',
    username: 'DividendDiva',
    market: 'Stocks',
    risk: 'Low',
    profit: '+38.9%',
    copiers: 4012,
    image: 'https://placehold.co/600x400.png',
    avatarSeed: 'DD',
    joined: '2020-03-15',
    strategy: 'Builds a diversified portfolio of high-yield dividend stocks to generate consistent income. Focus on stable, cash-flow positive companies.',
  }
];
